INPUT_SIZE = 100

COLUMN_COUNT = 100
COLUMN_HEIGHT = 5
TEMPORAL_CONNECTION_COUNT = 4

PERMENANCE_THRESHOLD = 0.5
INIT_PERMENANCE_RADIUS = 0.5

INHIBITION_RADIUS = 69
SPATIAL_CONNECTION_COUNT = 50
KTH_SCORE = 2

PERMENCANCE_INCREMENT = 0.03
PERMENCANCE_DECREAMENT = 0.01

LEARNING = True

class CELL_STATE:
    INACTIVE = 0
    ACTIVE = 1
    PREDICTING = 2