COLUMN_COUNT = 100
COLUMN_HEIGHT = 5
TEMPORAL_CONNECTION_COUNT = 4
PERMENANCE_THRESHOLD = 0.2
INHIBITION_RADIUS = 30
SPATIAL_CONNECTION_COUNT = 70
KTH_SCORE = 1

class CELL_STATE:
    INACTIVE = 0
    ACTIVE = 1
    PREDICTING = 2